language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
  - "pypy"
  - "pypy3"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest pytz tzlocal pymodbus pylogix
  - pip install 'argparse; python_version < "2.7"'
  - pip install 'configparser; python_version < "3.0"'
  - pip install 'ipaddress; python_version < "3.0"'

# command to run tests.
script:
  - make test
